export const TodoArr = [
    {
        title: "Today List",
        transform: 'translate(0, 0)',
        tasks: [
            { task: "Call Meeting" },
            { task: "Grossary Buy" },
            { task: "Take a Tour" },
            { task: "Meet Sanjay" },
            { task: "Read Coding Book" },
            { task: "Write an essay" },
            { task: "Call Meeting" },
            { task: "Grossary Buy" },
            { task: "Take a Tour" },
            { task: "Take a Tour" },
            { task: "Take a Tour" },
            { task: "Take a Tour" },
            { task: "Take a Tour" },
            { task: "Take a Tour" },
            { task: "Take a Tour" },
            { task: "Take a Tour" },
            { task: "Take a Tour" },
            { task: "Take a Tour" },
            { task: "Take a Tour" },
        ],
    },
    {
        title: "Today List",
        transform: 'translate(0, 0)',
        tasks: [
            { task: "Call Meeting" },
            { task: "Grossary Buy" },
            { task: "Take a Tour" },
        ],
    },
    {
        title: "Today List",
        transform: 'translate(0, 0)',
        tasks: [
            { task: "Call Meeting" },
            { task: "Grossary Buy" },
            { task: "Take a Tour" },
            { task: "Meet Sanjay" },
        ],
    },
    {
        title: "Today List",
        transform: 'translate(0, 0)',
        tasks: [
            { task: "Call Meeting" },
            { task: "Grossary Buy" },
            { task: "Take a Tour" },
            { task: "Meet Sanjay" },
            { task: "Read Coding Book" },
            { task: "Read Coding Book" },
            { task: "Read Coding Book" },
            { task: "Read Coding Book" },
            { task: "Read Coding Book" },
            { task: "Read Coding Book" },
            { task: "Read Coding Book" },
            { task: "Read Coding Book" },
            { task: "Read Coding Book" },
            { task: "Read Coding Book" },
            { task: "Write an essay" },
            { task: "Call Meeting" },
            { task: "Grossary Buy" },
            { task: "Take a Tour" },
        ],
    },
    {
        title: "Today List",
        transform: 'translate(0, 0)',
        tasks: [
            { task: "Call Meeting" },
        ],
    },
    {
        title: "Today List",
        transform: 'translate(0, 0)',
        tasks: [
            { task: "Call Meeting" },
            { task: "Grossary Buy" },
            { task: "Take a Tour" },
            { task: "Meet Sanjay" },
            { task: "Read Coding Book" },
        ],
    },
    {
        title: "Today List",
        transform: 'translate(0, 0)',
        tasks: [
            { task: "Call Meeting" },
            { task: "Grossary Buy" },
            { task: "Take a Tour" },
            { task: "Meet Sanjay" },
            { task: "Read Coding Book" },
            { task: "Write an essay" },
            { task: "Call Meeting" },
            { task: "Grossary Buy" },
            { task: "Grossary Buy" },
            { task: "Grossary Buy" },
            { task: "Grossary Buy" },
            { task: "Grossary Buy" },
            { task: "Grossary Buy" },
            { task: "Grossary Buy" },
            { task: "Grossary Buy" },
            { task: "Grossary Buy" },
            { task: "Grossary Buy" },
            { task: "Grossary Buy" },
            { task: "Grossary Buy" },
            { task: "Grossary Buy" },
            { task: "Grossary Buy" },
            { task: "Grossary Buy" },
            { task: "Grossary Buy" },
            { task: "Grossary Buy" },
            { task: "Grossary Buy" },
            { task: "Grossary Buy" },
            { task: "Grossary Buy" },
            { task: "Grossary Buy" },
            { task: "Grossary Buy" },
            { task: "Grossary Buy" },
            { task: "Grossary Buy" },
            { task: "Take a Tour" },
        ],
    },
    {
        title: "Today List",
        transform: 'translate(0, 0)',
        tasks: [
            { task: "Call Meeting" },
            { task: "Grossary Buy" },
            { task: "Take a Tour" },
            { task: "Meet Sanjay" },
        ],
    },
    {
        title: "Today List",
        transform: 'translate(0, 0)',
        tasks: [
            { task: "Call Meeting" },
            { task: "Grossary Buy" },
        ],
    },
    {
        title: "Today List",
        transform: 'translate(0, 0)',
        tasks: [
            { task: "Call Meeting" },
            { task: "Grossary Buy" },
            { task: "Take a Tour" },
            { task: "Meet Sanjay" },
            { task: "Read Coding Book" },
            { task: "Write an essay" },
            { task: "Call Meeting" },
            { task: "Grossary Buy" },
            { task: "Take a Tour" },
        ],
    },
];