export const USERS = {
  1: {
    id: 1,
    name: 'user1',
    email: 'user1@gmail.com',

    detail: ''
  },
  2: {
    id: 2,
    name: 'user2',
    email: 'user2@gmail.com',

    detail: ''
  },
  3: {
    id: 3,
    name: 'user3',
    email: 'user3@gmail.com',

    detail: ''
  },
  4: {
    id: 4,
    name: 'user4',
    email: 'user4@gmail.com',

    detail: ''
  },
  5: {
    id: 5,
    name: 'user5',
    email: 'user5@gmail.com',

    detail: ''
  },
  6: {
    id: 6,
    name: 'user6',
    email: 'user6@gmail.com',

    detail: ''
  },
  7: {
    id: 7,
    name: 'user7',
    email: 'user7@gmail.com',

    detail: ''
  },
  8: {
    id: 8,
    name: 'user8',
    email: 'user8@gmail.com',

    detail: ''
  },
  9: {
    id: 9,
    name: 'user9',
    email: 'user9@gmail.com',

    detail: ''
  },
  10: {
    id: 10,
    name: 'user10',
    email: 'user10@gmail.com',
    detail: ''
  },
  11: {
    id: 11,
    name: 'user11',
    email: 'user11@gmail.com',
    detail: ''
  },
  12: {
    id: 12,
    name: 'user12',
    email: 'user12@gmail.com',
    detail: ''
  },
  13: {
    id: 13,
    name: 'user13',
    email: 'user13@gmail.com',
    detail: ''
  },
  14: {
    id: 14,
    name: 'user14',
    email: 'user14@gmail.com',
    detail: ''
  },
  15: {
    id: 15,
    name: 'user15',
    email: 'user15@gmail.com',
    detail: ''
  },
};

export const DUTIESANDTAXESACC = {
  "CGST#Input": [
    {
      "Ref": 25909,
      "T_idF": 25909,
      "Audit": null,
      "IsAudit": null,
      "FirstName": "Admin",
      "RepName": null,
      "RepMobile": null,
      "MistryName": null,
      "MistryMobile": null,
      "IsCheck": "",
      "city": null,
      "Balance": "6363187.72 Db",
      "TransportName": null,
      "AccGroupName": "Duties & Taxes",
      "BID": 1,
      "AcOpBl": null,
      "AcOpCrDb": "Db",
      "BID1": 1,
      "AcClBl": 6363187.72,
      "AcClCrDb": "Db",
      "Cramt": 365513.49,
      "DbAmt": 6728701.21,
      "AccountId": 25909,
      "AccountName": "Purchase CGST 9%",
      "Alias": null,
      "CreditLimit": null,
      "CreditDay": null,
      "Email": null,
      "Address": null,
      "Address2": null,
      "Address3": null,
      "PANNO": null,
      "GSTNO": null,
      "PhoneO": null,
      "Mobile": null,
      "Mobile2": null,
      "AcOpBlValue": null,
      "AcClBlValue": 6363187.72,
      "PinCode": null,
      "state_name": null,
      "AreaName": null,
      "DsoDays": null,
      "AccountType": null,
      "AccSubType": "Input",
      "GIType": "CGST"
    },
    {
      "Ref": 25906,
      "T_idF": 25906,
      "Audit": null,
      "IsAudit": null,
      "FirstName": "Admin",
      "RepName": null,
      "RepMobile": null,
      "MistryName": null,
      "MistryMobile": null,
      "IsCheck": "",
      "city": null,
      "Balance": "5316.00 Db",
      "TransportName": null,
      "AccGroupName": "Duties & Taxes",
      "BID": 1,
      "AcOpBl": null,
      "AcOpCrDb": "Db",
      "BID1": 1,
      "AcClBl": 5316,
      "AcClCrDb": "Db",
      "Cramt": 9558,
      "DbAmt": 14874,
      "AccountId": 25906,
      "AccountName": "Purchase CGST 6%",
      "Alias": null,
      "CreditLimit": null,
      "CreditDay": null,
      "Email": null,
      "Address": null,
      "Address2": null,
      "Address3": null,
      "PANNO": null,
      "GSTNO": null,
      "PhoneO": null,
      "Mobile": null,
      "Mobile2": null,
      "AcOpBlValue": null,
      "AcClBlValue": 5316,
      "PinCode": null,
      "state_name": null,
      "AreaName": null,
      "DsoDays": null,
      "AccountType": null,
      "AccSubType": "Input",
      "GIType": "CGST"
    },
    {
      "Ref": 25903,
      "T_idF": 25903,
      "Audit": null,
      "IsAudit": null,
      "FirstName": "Admin",
      "RepName": null,
      "RepMobile": null,
      "MistryName": null,
      "MistryMobile": null,
      "IsCheck": "",
      "city": null,
      "Balance": "304558.11 Db",
      "TransportName": null,
      "AccGroupName": "Duties & Taxes",
      "BID": 1,
      "AcOpBl": null,
      "AcOpCrDb": "Db",
      "BID1": 1,
      "AcClBl": 304558.11,
      "AcClCrDb": "Db",
      "Cramt": 10713.62,
      "DbAmt": 315271.73,
      "AccountId": 25903,
      "AccountName": "Purchase CGST 2.5%",
      "Alias": null,
      "CreditLimit": null,
      "CreditDay": null,
      "Email": null,
      "Address": null,
      "Address2": null,
      "Address3": null,
      "PANNO": null,
      "GSTNO": null,
      "PhoneO": null,
      "Mobile": null,
      "Mobile2": null,
      "AcOpBlValue": null,
      "AcClBlValue": 304558.11,
      "PinCode": null,
      "state_name": null,
      "AreaName": null,
      "DsoDays": null,
      "AccountType": null,
      "AccSubType": "Input",
      "GIType": "CGST"
    },
    {
      "Ref": 25912,
      "T_idF": 25912,
      "Audit": null,
      "IsAudit": null,
      "FirstName": "Admin",
      "RepName": null,
      "RepMobile": null,
      "MistryName": null,
      "MistryMobile": null,
      "IsCheck": "",
      "city": null,
      "Balance": "0.00 Db",
      "TransportName": null,
      "AccGroupName": "Duties & Taxes",
      "BID": 1,
      "AcOpBl": null,
      "AcOpCrDb": "Db",
      "BID1": 1,
      "AcClBl": 0,
      "AcClCrDb": "Db",
      "Cramt": 0,
      "DbAmt": 0,
      "AccountId": 25912,
      "AccountName": "Purchase CGST 14%",
      "Alias": null,
      "CreditLimit": null,
      "CreditDay": null,
      "Email": null,
      "Address": null,
      "Address2": null,
      "Address3": null,
      "PANNO": null,
      "GSTNO": null,
      "PhoneO": null,
      "Mobile": null,
      "Mobile2": null,
      "AcOpBlValue": null,
      "AcClBlValue": 0,
      "PinCode": null,
      "state_name": null,
      "AreaName": null,
      "DsoDays": null,
      "AccountType": null,
      "AccSubType": "Input",
      "GIType": "CGST"
    },
    {
      "Ref": 25900,
      "T_idF": 25900,
      "Audit": null,
      "IsAudit": null,
      "FirstName": "Admin",
      "RepName": null,
      "RepMobile": null,
      "MistryName": null,
      "MistryMobile": null,
      "IsCheck": "",
      "city": null,
      "Balance": "390.30 Db",
      "TransportName": null,
      "AccGroupName": "Duties & Taxes",
      "BID": 1,
      "AcOpBl": null,
      "AcOpCrDb": "Db",
      "BID1": 1,
      "AcClBl": 390.3,
      "AcClCrDb": "Db",
      "Cramt": 0,
      "DbAmt": 390.3,
      "AccountId": 25900,
      "AccountName": "Purchase CGST 1.5%",
      "Alias": null,
      "CreditLimit": null,
      "CreditDay": null,
      "Email": null,
      "Address": null,
      "Address2": null,
      "Address3": null,
      "PANNO": null,
      "GSTNO": null,
      "PhoneO": null,
      "Mobile": null,
      "Mobile2": null,
      "AcOpBlValue": null,
      "AcClBlValue": 390.3,
      "PinCode": null,
      "state_name": null,
      "AreaName": null,
      "DsoDays": null,
      "AccountType": null,
      "AccSubType": "Input",
      "GIType": "CGST"
    }
  ],
  "IGST#Input": [
    {
      "Ref": 25905,
      "T_idF": 25905,
      "Audit": null,
      "IsAudit": null,
      "FirstName": "Admin",
      "RepName": null,
      "RepMobile": null,
      "MistryName": null,
      "MistryMobile": null,
      "IsCheck": "",
      "city": null,
      "Balance": "0.00 Db",
      "TransportName": null,
      "AccGroupName": "Duties & Taxes",
      "BID": 1,
      "AcOpBl": null,
      "AcOpCrDb": "Db",
      "BID1": 1,
      "AcClBl": 0,
      "AcClCrDb": "Db",
      "Cramt": 0,
      "DbAmt": 0,
      "AccountId": 25905,
      "AccountName": "Purchase IGST 5%",
      "Alias": null,
      "CreditLimit": null,
      "CreditDay": null,
      "Email": null,
      "Address": null,
      "Address2": null,
      "Address3": null,
      "PANNO": null,
      "GSTNO": null,
      "PhoneO": null,
      "Mobile": null,
      "Mobile2": null,
      "AcOpBlValue": null,
      "AcClBlValue": 0,
      "PinCode": null,
      "state_name": null,
      "AreaName": null,
      "DsoDays": null,
      "AccountType": null,
      "AccSubType": "Input",
      "GIType": "IGST"
    },
    {
      "Ref": 25902,
      "T_idF": 25902,
      "Audit": null,
      "IsAudit": null,
      "FirstName": "Admin",
      "RepName": null,
      "RepMobile": null,
      "MistryName": null,
      "MistryMobile": null,
      "IsCheck": "",
      "city": null,
      "Balance": "0.00 Db",
      "TransportName": null,
      "AccGroupName": "Duties & Taxes",
      "BID": 1,
      "AcOpBl": null,
      "AcOpCrDb": "Db",
      "BID1": 1,
      "AcClBl": 0,
      "AcClCrDb": "Db",
      "Cramt": 0,
      "DbAmt": 0,
      "AccountId": 25902,
      "AccountName": "Purchase IGST 3%",
      "Alias": null,
      "CreditLimit": null,
      "CreditDay": null,
      "Email": null,
      "Address": null,
      "Address2": null,
      "Address3": null,
      "PANNO": null,
      "GSTNO": null,
      "PhoneO": null,
      "Mobile": null,
      "Mobile2": null,
      "AcOpBlValue": null,
      "AcClBlValue": 0,
      "PinCode": null,
      "state_name": null,
      "AreaName": null,
      "DsoDays": null,
      "AccountType": null,
      "AccSubType": "Input",
      "GIType": "IGST"
    },
    {
      "Ref": 25914,
      "T_idF": 25914,
      "Audit": null,
      "IsAudit": null,
      "FirstName": "Admin",
      "RepName": null,
      "RepMobile": null,
      "MistryName": null,
      "MistryMobile": null,
      "IsCheck": "",
      "city": null,
      "Balance": "0.00 Db",
      "TransportName": null,
      "AccGroupName": "Duties & Taxes",
      "BID": 1,
      "AcOpBl": null,
      "AcOpCrDb": "Db",
      "BID1": 1,
      "AcClBl": 0,
      "AcClCrDb": "Db",
      "Cramt": 0,
      "DbAmt": 0,
      "AccountId": 25914,
      "AccountName": "Purchase IGST 28%",
      "Alias": null,
      "CreditLimit": null,
      "CreditDay": null,
      "Email": null,
      "Address": null,
      "Address2": null,
      "Address3": null,
      "PANNO": null,
      "GSTNO": null,
      "PhoneO": null,
      "Mobile": null,
      "Mobile2": null,
      "AcOpBlValue": null,
      "AcClBlValue": 0,
      "PinCode": null,
      "state_name": null,
      "AreaName": null,
      "DsoDays": null,
      "AccountType": null,
      "AccSubType": "Input",
      "GIType": "IGST"
    },
    {
      "Ref": 25911,
      "T_idF": 25911,
      "Audit": null,
      "IsAudit": null,
      "FirstName": "Admin",
      "RepName": null,
      "RepMobile": null,
      "MistryName": null,
      "MistryMobile": null,
      "IsCheck": "",
      "city": null,
      "Balance": "0.00 Db",
      "TransportName": null,
      "AccGroupName": "Duties & Taxes",
      "BID": 1,
      "AcOpBl": null,
      "AcOpCrDb": "Db",
      "BID1": 1,
      "AcClBl": 0,
      "AcClCrDb": "Db",
      "Cramt": 0,
      "DbAmt": 0,
      "AccountId": 25911,
      "AccountName": "Purchase IGST 18%",
      "Alias": null,
      "CreditLimit": null,
      "CreditDay": null,
      "Email": null,
      "Address": null,
      "Address2": null,
      "Address3": null,
      "PANNO": null,
      "GSTNO": null,
      "PhoneO": null,
      "Mobile": null,
      "Mobile2": null,
      "AcOpBlValue": null,
      "AcClBlValue": 0,
      "PinCode": null,
      "state_name": null,
      "AreaName": null,
      "DsoDays": null,
      "AccountType": null,
      "AccSubType": "Input",
      "GIType": "IGST"
    },
    {
      "Ref": 25908,
      "T_idF": 25908,
      "Audit": null,
      "IsAudit": null,
      "FirstName": "Admin",
      "RepName": null,
      "RepMobile": null,
      "MistryName": null,
      "MistryMobile": null,
      "IsCheck": "",
      "city": null,
      "Balance": "0.00 Db",
      "TransportName": null,
      "AccGroupName": "Duties & Taxes",
      "BID": 1,
      "AcOpBl": null,
      "AcOpCrDb": "Db",
      "BID1": 1,
      "AcClBl": 0,
      "AcClCrDb": "Db",
      "Cramt": 0,
      "DbAmt": 0,
      "AccountId": 25908,
      "AccountName": "Purchase IGST 12%",
      "Alias": null,
      "CreditLimit": null,
      "CreditDay": null,
      "Email": null,
      "Address": null,
      "Address2": null,
      "Address3": null,
      "PANNO": null,
      "GSTNO": null,
      "PhoneO": null,
      "Mobile": null,
      "Mobile2": null,
      "AcOpBlValue": null,
      "AcClBlValue": 0,
      "PinCode": null,
      "state_name": null,
      "AreaName": null,
      "DsoDays": null,
      "AccountType": null,
      "AccSubType": "Input",
      "GIType": "IGST"
    }
  ],
  "SGST#Input": [
    {
      "Ref": 25910,
      "T_idF": 25910,
      "Audit": null,
      "IsAudit": null,
      "FirstName": "Admin",
      "RepName": null,
      "RepMobile": null,
      "MistryName": null,
      "MistryMobile": null,
      "IsCheck": "",
      "city": null,
      "Balance": "6363187.72 Db",
      "TransportName": null,
      "AccGroupName": "Duties & Taxes",
      "BID": 1,
      "AcOpBl": null,
      "AcOpCrDb": "Db",
      "BID1": 1,
      "AcClBl": 6363187.72,
      "AcClCrDb": "Db",
      "Cramt": 365513.49,
      "DbAmt": 6728701.21,
      "AccountId": 25910,
      "AccountName": "Purchase SGST 9%",
      "Alias": null,
      "CreditLimit": null,
      "CreditDay": null,
      "Email": null,
      "Address": null,
      "Address2": null,
      "Address3": null,
      "PANNO": null,
      "GSTNO": null,
      "PhoneO": null,
      "Mobile": null,
      "Mobile2": null,
      "AcOpBlValue": null,
      "AcClBlValue": 6363187.72,
      "PinCode": null,
      "state_name": null,
      "AreaName": null,
      "DsoDays": null,
      "AccountType": null,
      "AccSubType": "Input",
      "GIType": "SGST"
    },
    {
      "Ref": 25907,
      "T_idF": 25907,
      "Audit": null,
      "IsAudit": null,
      "FirstName": "Admin",
      "RepName": null,
      "RepMobile": null,
      "MistryName": null,
      "MistryMobile": null,
      "IsCheck": "",
      "city": null,
      "Balance": "5316.00 Db",
      "TransportName": null,
      "AccGroupName": "Duties & Taxes",
      "BID": 1,
      "AcOpBl": null,
      "AcOpCrDb": "Db",
      "BID1": 1,
      "AcClBl": 5316,
      "AcClCrDb": "Db",
      "Cramt": 9558,
      "DbAmt": 14874,
      "AccountId": 25907,
      "AccountName": "Purchase SGST 6%",
      "Alias": null,
      "CreditLimit": null,
      "CreditDay": null,
      "Email": null,
      "Address": null,
      "Address2": null,
      "Address3": null,
      "PANNO": null,
      "GSTNO": null,
      "PhoneO": null,
      "Mobile": null,
      "Mobile2": null,
      "AcOpBlValue": null,
      "AcClBlValue": 5316,
      "PinCode": null,
      "state_name": null,
      "AreaName": null,
      "DsoDays": null,
      "AccountType": null,
      "AccSubType": "Input",
      "GIType": "SGST"
    },
    {
      "Ref": 25904,
      "T_idF": 25904,
      "Audit": null,
      "IsAudit": null,
      "FirstName": "Admin",
      "RepName": null,
      "RepMobile": null,
      "MistryName": null,
      "MistryMobile": null,
      "IsCheck": "",
      "city": null,
      "Balance": "304558.11 Db",
      "TransportName": null,
      "AccGroupName": "Duties & Taxes",
      "BID": 1,
      "AcOpBl": null,
      "AcOpCrDb": "Db",
      "BID1": 1,
      "AcClBl": 304558.11,
      "AcClCrDb": "Db",
      "Cramt": 10713.62,
      "DbAmt": 315271.73,
      "AccountId": 25904,
      "AccountName": "Purchase SGST 2.5%",
      "Alias": null,
      "CreditLimit": null,
      "CreditDay": null,
      "Email": null,
      "Address": null,
      "Address2": null,
      "Address3": null,
      "PANNO": null,
      "GSTNO": null,
      "PhoneO": null,
      "Mobile": null,
      "Mobile2": null,
      "AcOpBlValue": null,
      "AcClBlValue": 304558.11,
      "PinCode": null,
      "state_name": null,
      "AreaName": null,
      "DsoDays": null,
      "AccountType": null,
      "AccSubType": "Input",
      "GIType": "SGST"
    },
    {
      "Ref": 25913,
      "T_idF": 25913,
      "Audit": null,
      "IsAudit": null,
      "FirstName": "Admin",
      "RepName": null,
      "RepMobile": null,
      "MistryName": null,
      "MistryMobile": null,
      "IsCheck": "",
      "city": null,
      "Balance": "0.00 Db",
      "TransportName": null,
      "AccGroupName": "Duties & Taxes",
      "BID": 1,
      "AcOpBl": null,
      "AcOpCrDb": "Db",
      "BID1": 1,
      "AcClBl": 0,
      "AcClCrDb": "Db",
      "Cramt": 0,
      "DbAmt": 0,
      "AccountId": 25913,
      "AccountName": "Purchase SGST 14%",
      "Alias": null,
      "CreditLimit": null,
      "CreditDay": null,
      "Email": null,
      "Address": null,
      "Address2": null,
      "Address3": null,
      "PANNO": null,
      "GSTNO": null,
      "PhoneO": null,
      "Mobile": null,
      "Mobile2": null,
      "AcOpBlValue": null,
      "AcClBlValue": 0,
      "PinCode": null,
      "state_name": null,
      "AreaName": null,
      "DsoDays": null,
      "AccountType": null,
      "AccSubType": "Input",
      "GIType": "SGST"
    }
  ],
  "CGST#Output": [
    {
      "Ref": 25769,
      "T_idF": 25769,
      "Audit": null,
      "IsAudit": null,
      "FirstName": "Admin",
      "RepName": null,
      "RepMobile": null,
      "MistryName": null,
      "MistryMobile": null,
      "IsCheck": "",
      "city": null,
      "Balance": "4085963.23 Cr",
      "TransportName": null,
      "AccGroupName": "Duties & Taxes",
      "BID": 1,
      "AcOpBl": null,
      "AcOpCrDb": "Db",
      "BID1": 1,
      "AcClBl": 4085963.23,
      "AcClCrDb": "Cr",
      "Cramt": 4321352,
      "DbAmt": 235388.77,
      "AccountId": 25769,
      "AccountName": "SALES CGST 9%",
      "Alias": null,
      "CreditLimit": null,
      "CreditDay": null,
      "Email": null,
      "Address": null,
      "Address2": null,
      "Address3": null,
      "PANNO": null,
      "GSTNO": null,
      "PhoneO": null,
      "Mobile": null,
      "Mobile2": null,
      "AcOpBlValue": null,
      "AcClBlValue": -4085963.23,
      "PinCode": null,
      "state_name": null,
      "AreaName": null,
      "DsoDays": null,
      "AccountType": null,
      "AccSubType": "Output",
      "GIType": "CGST"
    },
    {
      "Ref": 25766,
      "T_idF": 25766,
      "Audit": null,
      "IsAudit": null,
      "FirstName": "Admin",
      "RepName": null,
      "RepMobile": null,
      "MistryName": null,
      "MistryMobile": null,
      "IsCheck": "",
      "city": null,
      "Balance": "7976.12 Cr",
      "TransportName": null,
      "AccGroupName": "Duties & Taxes",
      "BID": 1,
      "AcOpBl": null,
      "AcOpCrDb": "Db",
      "BID1": 1,
      "AcClBl": 7976.12,
      "AcClCrDb": "Cr",
      "Cramt": 12628.63,
      "DbAmt": 4652.51,
      "AccountId": 25766,
      "AccountName": "SALES CGST 6%",
      "Alias": null,
      "CreditLimit": null,
      "CreditDay": null,
      "Email": null,
      "Address": null,
      "Address2": null,
      "Address3": null,
      "PANNO": null,
      "GSTNO": null,
      "PhoneO": null,
      "Mobile": null,
      "Mobile2": null,
      "AcOpBlValue": null,
      "AcClBlValue": -7976.12,
      "PinCode": null,
      "state_name": null,
      "AreaName": null,
      "DsoDays": null,
      "AccountType": null,
      "AccSubType": "Output",
      "GIType": "CGST"
    },
    {
      "Ref": 25763,
      "T_idF": 25763,
      "Audit": null,
      "IsAudit": null,
      "FirstName": "Admin",
      "RepName": null,
      "RepMobile": null,
      "MistryName": null,
      "MistryMobile": null,
      "IsCheck": "",
      "city": null,
      "Balance": "478025.97 Cr",
      "TransportName": null,
      "AccGroupName": "Duties & Taxes",
      "BID": 1,
      "AcOpBl": null,
      "AcOpCrDb": "Db",
      "BID1": 1,
      "AcClBl": 478025.97,
      "AcClCrDb": "Cr",
      "Cramt": 501585.61,
      "DbAmt": 23559.64,
      "AccountId": 25763,
      "AccountName": "SALES CGST 2.5%",
      "Alias": null,
      "CreditLimit": null,
      "CreditDay": null,
      "Email": null,
      "Address": null,
      "Address2": null,
      "Address3": null,
      "PANNO": null,
      "GSTNO": null,
      "PhoneO": null,
      "Mobile": null,
      "Mobile2": null,
      "AcOpBlValue": null,
      "AcClBlValue": -478025.97,
      "PinCode": null,
      "state_name": null,
      "AreaName": null,
      "DsoDays": null,
      "AccountType": null,
      "AccSubType": "Output",
      "GIType": "CGST"
    },
    {
      "Ref": 25772,
      "T_idF": 25772,
      "Audit": null,
      "IsAudit": null,
      "FirstName": "Admin",
      "RepName": null,
      "RepMobile": null,
      "MistryName": null,
      "MistryMobile": null,
      "IsCheck": "",
      "city": null,
      "Balance": "0.00 Db",
      "TransportName": null,
      "AccGroupName": "Duties & Taxes",
      "BID": 1,
      "AcOpBl": null,
      "AcOpCrDb": "Db",
      "BID1": 1,
      "AcClBl": 0,
      "AcClCrDb": "Db",
      "Cramt": 0,
      "DbAmt": 0,
      "AccountId": 25772,
      "AccountName": "SALES CGST 14%",
      "Alias": null,
      "CreditLimit": null,
      "CreditDay": null,
      "Email": null,
      "Address": null,
      "Address2": null,
      "Address3": null,
      "PANNO": null,
      "GSTNO": null,
      "PhoneO": null,
      "Mobile": null,
      "Mobile2": null,
      "AcOpBlValue": null,
      "AcClBlValue": 0,
      "PinCode": null,
      "state_name": null,
      "AreaName": null,
      "DsoDays": null,
      "AccountType": null,
      "AccSubType": "Output",
      "GIType": "CGST"
    },
    {
      "Ref": 25776,
      "T_idF": 25776,
      "Audit": null,
      "IsAudit": null,
      "FirstName": "Admin",
      "RepName": null,
      "RepMobile": null,
      "MistryName": null,
      "MistryMobile": null,
      "IsCheck": "",
      "city": null,
      "Balance": "0.00 Db",
      "TransportName": null,
      "AccGroupName": "Duties & Taxes",
      "BID": 1,
      "AcOpBl": null,
      "AcOpCrDb": "Db",
      "BID1": 1,
      "AcClBl": 0,
      "AcClCrDb": "Db",
      "Cramt": 0,
      "DbAmt": 0,
      "AccountId": 25776,
      "AccountName": "SALES CGST 1.5%",
      "Alias": null,
      "CreditLimit": null,
      "CreditDay": null,
      "Email": null,
      "Address": null,
      "Address2": null,
      "Address3": null,
      "PANNO": null,
      "GSTNO": null,
      "PhoneO": null,
      "Mobile": null,
      "Mobile2": null,
      "AcOpBlValue": null,
      "AcClBlValue": 0,
      "PinCode": null,
      "state_name": null,
      "AreaName": null,
      "DsoDays": null,
      "AccountType": null,
      "AccSubType": "Output",
      "GIType": "CGST"
    }
  ],
  "IGST#Output": [
    {
      "Ref": 25765,
      "T_idF": 25765,
      "Audit": null,
      "IsAudit": null,
      "FirstName": "Admin",
      "RepName": null,
      "RepMobile": null,
      "MistryName": null,
      "MistryMobile": null,
      "IsCheck": "",
      "city": null,
      "Balance": "466266.45 Cr",
      "TransportName": null,
      "AccGroupName": "Duties & Taxes",
      "BID": 1,
      "AcOpBl": null,
      "AcOpCrDb": "Db",
      "BID1": 1,
      "AcClBl": 466266.45,
      "AcClCrDb": "Cr",
      "Cramt": 466396.45,
      "DbAmt": 130,
      "AccountId": 25765,
      "AccountName": "SALES IGST 5%",
      "Alias": null,
      "CreditLimit": null,
      "CreditDay": null,
      "Email": null,
      "Address": null,
      "Address2": null,
      "Address3": null,
      "PANNO": null,
      "GSTNO": null,
      "PhoneO": null,
      "Mobile": null,
      "Mobile2": null,
      "AcOpBlValue": null,
      "AcClBlValue": -466266.45,
      "PinCode": null,
      "state_name": null,
      "AreaName": null,
      "DsoDays": null,
      "AccountType": null,
      "AccSubType": "Output",
      "GIType": "IGST"
    },
    {
      "Ref": 25778,
      "T_idF": 25778,
      "Audit": null,
      "IsAudit": null,
      "FirstName": "Admin",
      "RepName": null,
      "RepMobile": null,
      "MistryName": null,
      "MistryMobile": null,
      "IsCheck": "",
      "city": null,
      "Balance": "0.00 Db",
      "TransportName": null,
      "AccGroupName": "Duties & Taxes",
      "BID": 1,
      "AcOpBl": null,
      "AcOpCrDb": "Db",
      "BID1": 1,
      "AcClBl": 0,
      "AcClCrDb": "Db",
      "Cramt": 0,
      "DbAmt": 0,
      "AccountId": 25778,
      "AccountName": "SALES IGST 3%",
      "Alias": null,
      "CreditLimit": null,
      "CreditDay": null,
      "Email": null,
      "Address": null,
      "Address2": null,
      "Address3": null,
      "PANNO": null,
      "GSTNO": null,
      "PhoneO": null,
      "Mobile": null,
      "Mobile2": null,
      "AcOpBlValue": null,
      "AcClBlValue": 0,
      "PinCode": null,
      "state_name": null,
      "AreaName": null,
      "DsoDays": null,
      "AccountType": null,
      "AccSubType": "Output",
      "GIType": "IGST"
    },
    {
      "Ref": 25774,
      "T_idF": 25774,
      "Audit": null,
      "IsAudit": null,
      "FirstName": "Admin",
      "RepName": null,
      "RepMobile": null,
      "MistryName": null,
      "MistryMobile": null,
      "IsCheck": "",
      "city": null,
      "Balance": "0.00 Db",
      "TransportName": null,
      "AccGroupName": "Duties & Taxes",
      "BID": 1,
      "AcOpBl": null,
      "AcOpCrDb": "Db",
      "BID1": 1,
      "AcClBl": 0,
      "AcClCrDb": "Db",
      "Cramt": 0,
      "DbAmt": 0,
      "AccountId": 25774,
      "AccountName": "SALES IGST 28%",
      "Alias": null,
      "CreditLimit": null,
      "CreditDay": null,
      "Email": null,
      "Address": null,
      "Address2": null,
      "Address3": null,
      "PANNO": null,
      "GSTNO": null,
      "PhoneO": null,
      "Mobile": null,
      "Mobile2": null,
      "AcOpBlValue": null,
      "AcClBlValue": 0,
      "PinCode": null,
      "state_name": null,
      "AreaName": null,
      "DsoDays": null,
      "AccountType": null,
      "AccSubType": "Output",
      "GIType": "IGST"
    },
    {
      "Ref": 25771,
      "T_idF": 25771,
      "Audit": null,
      "IsAudit": null,
      "FirstName": "Admin",
      "RepName": null,
      "RepMobile": null,
      "MistryName": null,
      "MistryMobile": null,
      "IsCheck": "",
      "city": null,
      "Balance": "8160677.94 Cr",
      "TransportName": null,
      "AccGroupName": "Duties & Taxes",
      "BID": 1,
      "AcOpBl": null,
      "AcOpCrDb": "Db",
      "BID1": 1,
      "AcClBl": 8160677.94,
      "AcClCrDb": "Cr",
      "Cramt": 8798724.62,
      "DbAmt": 638046.68,
      "AccountId": 25771,
      "AccountName": "SALES IGST 18%",
      "Alias": null,
      "CreditLimit": null,
      "CreditDay": null,
      "Email": null,
      "Address": null,
      "Address2": null,
      "Address3": null,
      "PANNO": null,
      "GSTNO": null,
      "PhoneO": null,
      "Mobile": null,
      "Mobile2": null,
      "AcOpBlValue": null,
      "AcClBlValue": -8160677.94,
      "PinCode": null,
      "state_name": null,
      "AreaName": null,
      "DsoDays": null,
      "AccountType": null,
      "AccSubType": "Output",
      "GIType": "IGST"
    },
    {
      "Ref": 25768,
      "T_idF": 25768,
      "Audit": null,
      "IsAudit": null,
      "FirstName": "Admin",
      "RepName": null,
      "RepMobile": null,
      "MistryName": null,
      "MistryMobile": null,
      "IsCheck": "",
      "city": null,
      "Balance": "23604.00 Cr",
      "TransportName": null,
      "AccGroupName": "Duties & Taxes",
      "BID": 1,
      "AcOpBl": null,
      "AcOpCrDb": "Db",
      "BID1": 1,
      "AcClBl": 23604,
      "AcClCrDb": "Cr",
      "Cramt": 44421,
      "DbAmt": 20817,
      "AccountId": 25768,
      "AccountName": "SALES IGST 12%",
      "Alias": null,
      "CreditLimit": null,
      "CreditDay": null,
      "Email": null,
      "Address": null,
      "Address2": null,
      "Address3": null,
      "PANNO": null,
      "GSTNO": null,
      "PhoneO": null,
      "Mobile": null,
      "Mobile2": null,
      "AcOpBlValue": null,
      "AcClBlValue": -23604,
      "PinCode": null,
      "state_name": null,
      "AreaName": null,
      "DsoDays": null,
      "AccountType": null,
      "AccSubType": "Output",
      "GIType": "IGST"
    }
  ],
  "SGST#Output": [
    {
      "Ref": 25770,
      "T_idF": 25770,
      "Audit": null,
      "IsAudit": null,
      "FirstName": "Admin",
      "RepName": null,
      "RepMobile": null,
      "MistryName": null,
      "MistryMobile": null,
      "IsCheck": "",
      "city": null,
      "Balance": "4085963.23 Cr",
      "TransportName": null,
      "AccGroupName": "Duties & Taxes",
      "BID": 1,
      "AcOpBl": null,
      "AcOpCrDb": "Db",
      "BID1": 1,
      "AcClBl": 4085963.23,
      "AcClCrDb": "Cr",
      "Cramt": 4321352,
      "DbAmt": 235388.77,
      "AccountId": 25770,
      "AccountName": "SALES SGST 9%",
      "Alias": null,
      "CreditLimit": null,
      "CreditDay": null,
      "Email": null,
      "Address": null,
      "Address2": null,
      "Address3": null,
      "PANNO": null,
      "GSTNO": null,
      "PhoneO": null,
      "Mobile": null,
      "Mobile2": null,
      "AcOpBlValue": null,
      "AcClBlValue": -4085963.23,
      "PinCode": null,
      "state_name": null,
      "AreaName": null,
      "DsoDays": null,
      "AccountType": null,
      "AccSubType": "Output",
      "GIType": "SGST"
    },
    {
      "Ref": 25764,
      "T_idF": 25764,
      "Audit": null,
      "IsAudit": null,
      "FirstName": "Admin",
      "RepName": null,
      "RepMobile": null,
      "MistryName": null,
      "MistryMobile": null,
      "IsCheck": "",
      "city": null,
      "Balance": "478025.97 Cr",
      "TransportName": null,
      "AccGroupName": "Duties & Taxes",
      "BID": 1,
      "AcOpBl": null,
      "AcOpCrDb": "Db",
      "BID1": 1,
      "AcClBl": 478025.97,
      "AcClCrDb": "Cr",
      "Cramt": 501585.61,
      "DbAmt": 23559.64,
      "AccountId": 25764,
      "AccountName": "SALES SGST 2.5%",
      "Alias": null,
      "CreditLimit": null,
      "CreditDay": null,
      "Email": null,
      "Address": null,
      "Address2": null,
      "Address3": null,
      "PANNO": null,
      "GSTNO": null,
      "PhoneO": null,
      "Mobile": null,
      "Mobile2": null,
      "AcOpBlValue": null,
      "AcClBlValue": -478025.97,
      "PinCode": null,
      "state_name": null,
      "AreaName": null,
      "DsoDays": null,
      "AccountType": null,
      "AccSubType": "Output",
      "GIType": "SGST"
    },
    {
      "Ref": 25773,
      "T_idF": 25773,
      "Audit": null,
      "IsAudit": null,
      "FirstName": "Admin",
      "RepName": null,
      "RepMobile": null,
      "MistryName": null,
      "MistryMobile": null,
      "IsCheck": "",
      "city": null,
      "Balance": "0.00 Db",
      "TransportName": null,
      "AccGroupName": "Duties & Taxes",
      "BID": 1,
      "AcOpBl": null,
      "AcOpCrDb": "Db",
      "BID1": 1,
      "AcClBl": 0,
      "AcClCrDb": "Db",
      "Cramt": 0,
      "DbAmt": 0,
      "AccountId": 25773,
      "AccountName": "SALES SGST 14%",
      "Alias": null,
      "CreditLimit": null,
      "CreditDay": null,
      "Email": null,
      "Address": null,
      "Address2": null,
      "Address3": null,
      "PANNO": null,
      "GSTNO": null,
      "PhoneO": null,
      "Mobile": null,
      "Mobile2": null,
      "AcOpBlValue": null,
      "AcClBlValue": 0,
      "PinCode": null,
      "state_name": null,
      "AreaName": null,
      "DsoDays": null,
      "AccountType": null,
      "AccSubType": "Output",
      "GIType": "SGST"
    },
    {
      "Ref": 25777,
      "T_idF": 25777,
      "Audit": null,
      "IsAudit": null,
      "FirstName": "Admin",
      "RepName": null,
      "RepMobile": null,
      "MistryName": null,
      "MistryMobile": null,
      "IsCheck": "",
      "city": null,
      "Balance": "0.00 Db",
      "TransportName": null,
      "AccGroupName": "Duties & Taxes",
      "BID": 1,
      "AcOpBl": null,
      "AcOpCrDb": "Db",
      "BID1": 1,
      "AcClBl": 0,
      "AcClCrDb": "Db",
      "Cramt": 0,
      "DbAmt": 0,
      "AccountId": 25777,
      "AccountName": "SALES SGST 1.5%",
      "Alias": null,
      "CreditLimit": null,
      "CreditDay": null,
      "Email": null,
      "Address": null,
      "Address2": null,
      "Address3": null,
      "PANNO": null,
      "GSTNO": null,
      "PhoneO": null,
      "Mobile": null,
      "Mobile2": null,
      "AcOpBlValue": null,
      "AcClBlValue": 0,
      "PinCode": null,
      "state_name": null,
      "AreaName": null,
      "DsoDays": null,
      "AccountType": null,
      "AccSubType": "Output",
      "GIType": "SGST"
    }
  ]
}

export const NEWDUTIESANDTAXESACC = {
  1: {
    "CGST#Input": [
      {
        "AcClBl": 390.3,
        "AccountName": "Purchase CGST 1.5%",
        "AccountId": 25900,
        "AcClCrDb": "Db",
        "GIType": "CGST",
        "IsClear": false
      },
      {
        "AcClBl": 304558.11,
        "AccountName": "Purchase CGST 2.5%",
        "AccountId": 25903,
        "AcClCrDb": "Db",
        "GIType": "CGST",
        "IsClear": false
      },
      {
        "AcClBl": 5316,
        "AccountName": "Purchase CGST 6%",
        "AccountId": 25906,
        "AcClCrDb": "Db",
        "GIType": "CGST",
        "IsClear": false
      },
      {
        "AcClBl": 6363187.72,
        "AccountName": "Purchase CGST 9%",
        "AccountId": 25909,
        "AcClCrDb": "Db",
        "GIType": "CGST",
        "IsClear": false
      },
      {
        "AcClBl": 0,
        "AccountName": "Purchase CGST 14%",
        "AccountId": 25912,
        "AcClCrDb": "Db",
        "GIType": "CGST",
        "IsClear": false
      }
    ],
    "IGST#Input": [
      {
        "AcClBl": 0,
        "AccountName": "Purchase IGST 3%",
        "AccountId": 25902,
        "AcClCrDb": "Db",
        "GIType": "IGST",
        "IsClear": false
      },
      {
        "AcClBl": 0,
        "AccountName": "Purchase IGST 5%",
        "AccountId": 25905,
        "AcClCrDb": "Db",
        "GIType": "IGST",
        "IsClear": false
      },
      {
        "AcClBl": 0,
        "AccountName": "Purchase IGST 12%",
        "AccountId": 25908,
        "AcClCrDb": "Db",
        "GIType": "IGST",
        "IsClear": false
      },
      {
        "AcClBl": 0,
        "AccountName": "Purchase IGST 18%",
        "AccountId": 25911,
        "AcClCrDb": "Db",
        "GIType": "IGST",
        "IsClear": false
      },
      {
        "AcClBl": 0,
        "AccountName": "Purchase IGST 28%",
        "AccountId": 25914,
        "AcClCrDb": "Db",
        "GIType": "IGST",
        "IsClear": false
      }
    ],
    "SGST#Input": [
      {
        "AcClBl": 304558.11,
        "AccountName": "Purchase SGST 2.5%",
        "AccountId": 25904,
        "AcClCrDb": "Db",
        "GIType": "SGST",
        "IsClear": false
      },
      {
        "AcClBl": 5316,
        "AccountName": "Purchase SGST 6%",
        "AccountId": 25907,
        "AcClCrDb": "Db",
        "GIType": "SGST",
        "IsClear": false
      },
      {
        "AcClBl": 6363187.72,
        "AccountName": "Purchase SGST 9%",
        "AccountId": 25910,
        "AcClCrDb": "Db",
        "GIType": "SGST",
        "IsClear": false
      },
      {
        "AcClBl": 0,
        "AccountName": "Purchase SGST 14%",
        "AccountId": 25913,
        "AcClCrDb": "Db",
        "GIType": "SGST",
        "IsClear": false
      }
    ],
    "CGST#Output": [
      {
        "AcClBl": 0,
        "AccountName": "SALES CGST 1.5%",
        "AccountId": 25776,
        "AcClCrDb": "Db",
        "GIType": "CGST",
        "IsClear": false
      },
      {
        "AcClBl": 478025.97,
        "AccountName": "SALES CGST 2.5%",
        "AccountId": 25763,
        "AcClCrDb": "Cr",
        "GIType": "CGST",
        "IsClear": false
      },
      {
        "AcClBl": 7976.12,
        "AccountName": "SALES CGST 6%",
        "AccountId": 25766,
        "AcClCrDb": "Cr",
        "GIType": "CGST",
        "IsClear": false
      },
      {
        "AcClBl": 4085963.23,
        "AccountName": "SALES CGST 9%",
        "AccountId": 25769,
        "AcClCrDb": "Cr",
        "GIType": "CGST",
        "IsClear": false
      },
      {
        "AcClBl": 0,
        "AccountName": "SALES CGST 14%",
        "AccountId": 25772,
        "AcClCrDb": "Db",
        "GIType": "CGST",
        "IsClear": false
      }
    ],
    "IGST#Output": [
      {
        "AcClBl": 0,
        "AccountName": "SALES IGST 3%",
        "AccountId": 25778,
        "AcClCrDb": "Db",
        "GIType": "IGST",
        "IsClear": false
      },
      {
        "AcClBl": 466266.45,
        "AccountName": "SALES IGST 5%",
        "AccountId": 25765,
        "AcClCrDb": "Cr",
        "GIType": "IGST",
        "IsClear": false
      },
      {
        "AcClBl": 23604,
        "AccountName": "SALES IGST 12%",
        "AccountId": 25768,
        "AcClCrDb": "Cr",
        "GIType": "IGST",
        "IsClear": false
      },
      {
        "AcClBl": 8160677.94,
        "AccountName": "SALES IGST 18%",
        "AccountId": 25771,
        "AcClCrDb": "Cr",
        "GIType": "IGST",
        "IsClear": false
      },
      {
        "AcClBl": 0,
        "AccountName": "SALES IGST 28%",
        "AccountId": 25774,
        "AcClCrDb": "Db",
        "GIType": "IGST",
        "IsClear": false
      }
    ],
    "SGST#Output": [
      {
        "AcClBl": 0,
        "AccountName": "SALES SGST 1.5%",
        "AccountId": 25777,
        "AcClCrDb": "Db",
        "GIType": "SGST",
        "IsClear": false
      },
      {
        "AcClBl": 478025.97,
        "AccountName": "SALES SGST 2.5%",
        "AccountId": 25764,
        "AcClCrDb": "Cr",
        "GIType": "SGST",
        "IsClear": false
      },
      {
        "AcClBl": 4085963.23,
        "AccountName": "SALES SGST 9%",
        "AccountId": 25770,
        "AcClCrDb": "Cr",
        "GIType": "SGST",
        "IsClear": false
      },
      {
        "AcClBl": 0,
        "AccountName": "SALES SGST 14%",
        "AccountId": 25773,
        "AcClCrDb": "Db",
        "GIType": "SGST",
        "IsClear": false
      }
    ]
  },
  2: {
    "CGST#Input": [
      {
        "AcClBl": 390.3,
        "AccountName": "Purchase CGST 1.5%",
        "AccountId": 25900,
        "AcClCrDb": "Db",
        "GIType": "CGST",
        "IsClear": false
      },
      {
        "AcClBl": 304558.11,
        "AccountName": "Purchase CGST 2.5%",
        "AccountId": 25903,
        "AcClCrDb": "Db",
        "GIType": "CGST",
        "IsClear": false
      },
      {
        "AcClBl": 5316,
        "AccountName": "Purchase CGST 6%",
        "AccountId": 25906,
        "AcClCrDb": "Db",
        "GIType": "CGST",
        "IsClear": false
      },
      {
        "AcClBl": 6363187.72,
        "AccountName": "Purchase CGST 9%",
        "AccountId": 25909,
        "AcClCrDb": "Db",
        "GIType": "CGST",
        "IsClear": false
      },
      {
        "AcClBl": 0,
        "AccountName": "Purchase CGST 14%",
        "AccountId": 25912,
        "AcClCrDb": "Db",
        "GIType": "CGST",
        "IsClear": false
      }
    ],
    "IGST#Input": [
      {
        "AcClBl": 0,
        "AccountName": "Purchase IGST 3%",
        "AccountId": 25902,
        "AcClCrDb": "Db",
        "GIType": "IGST",
        "IsClear": false
      },
      {
        "AcClBl": 0,
        "AccountName": "Purchase IGST 5%",
        "AccountId": 25905,
        "AcClCrDb": "Db",
        "GIType": "IGST",
        "IsClear": false
      },
      {
        "AcClBl": 0,
        "AccountName": "Purchase IGST 12%",
        "AccountId": 25908,
        "AcClCrDb": "Db",
        "GIType": "IGST",
        "IsClear": false
      },
      {
        "AcClBl": 0,
        "AccountName": "Purchase IGST 18%",
        "AccountId": 25911,
        "AcClCrDb": "Db",
        "GIType": "IGST",
        "IsClear": false
      },
      {
        "AcClBl": 0,
        "AccountName": "Purchase IGST 28%",
        "AccountId": 25914,
        "AcClCrDb": "Db",
        "GIType": "IGST",
        "IsClear": false
      }
    ],
    "SGST#Input": [
      {
        "AcClBl": 304558.11,
        "AccountName": "Purchase SGST 2.5%",
        "AccountId": 25904,
        "AcClCrDb": "Db",
        "GIType": "SGST",
        "IsClear": false
      },
      {
        "AcClBl": 5316,
        "AccountName": "Purchase SGST 6%",
        "AccountId": 25907,
        "AcClCrDb": "Db",
        "GIType": "SGST",
        "IsClear": false
      },
      {
        "AcClBl": 6363187.72,
        "AccountName": "Purchase SGST 9%",
        "AccountId": 25910,
        "AcClCrDb": "Db",
        "GIType": "SGST",
        "IsClear": false
      },
      {
        "AcClBl": 0,
        "AccountName": "Purchase SGST 14%",
        "AccountId": 25913,
        "AcClCrDb": "Db",
        "GIType": "SGST",
        "IsClear": false
      }
    ],
    "CGST#Output": [
      {
        "AcClBl": 0,
        "AccountName": "SALES CGST 1.5%",
        "AccountId": 25776,
        "AcClCrDb": "Db",
        "GIType": "CGST",
        "IsClear": false
      },
      {
        "AcClBl": 478025.97,
        "AccountName": "SALES CGST 2.5%",
        "AccountId": 25763,
        "AcClCrDb": "Cr",
        "GIType": "CGST",
        "IsClear": false
      },
      {
        "AcClBl": 7976.12,
        "AccountName": "SALES CGST 6%",
        "AccountId": 25766,
        "AcClCrDb": "Cr",
        "GIType": "CGST",
        "IsClear": false
      },
      {
        "AcClBl": 8085963.23,
        "AccountName": "SALES CGST 9%",
        "AccountId": 25769,
        "AcClCrDb": "Cr",
        "GIType": "CGST",
        "IsClear": false
      },
      {
        "AcClBl": 0,
        "AccountName": "SALES CGST 14%",
        "AccountId": 25772,
        "AcClCrDb": "Db",
        "GIType": "CGST",
        "IsClear": false
      }
    ],
    "IGST#Output": [
      {
        "AcClBl": 0,
        "AccountName": "SALES IGST 3%",
        "AccountId": 25778,
        "AcClCrDb": "Db",
        "GIType": "IGST",
        "IsClear": false
      },
      {
        "AcClBl": 466266.45,
        "AccountName": "SALES IGST 5%",
        "AccountId": 25765,
        "AcClCrDb": "Cr",
        "GIType": "IGST",
        "IsClear": false
      },
      {
        "AcClBl": 23604,
        "AccountName": "SALES IGST 12%",
        "AccountId": 25768,
        "AcClCrDb": "Cr",
        "GIType": "IGST",
        "IsClear": false
      },
      {
        "AcClBl": 8160677.94,
        "AccountName": "SALES IGST 18%",
        "AccountId": 25771,
        "AcClCrDb": "Cr",
        "GIType": "IGST",
        "IsClear": false
      },
      {
        "AcClBl": 0,
        "AccountName": "SALES IGST 28%",
        "AccountId": 25774,
        "AcClCrDb": "Db",
        "GIType": "IGST",
        "IsClear": false
      }
    ],
    "SGST#Output": [
      {
        "AcClBl": 0,
        "AccountName": "SALES SGST 1.5%",
        "AccountId": 25777,
        "AcClCrDb": "Db",
        "GIType": "SGST",
        "IsClear": false
      },
      {
        "AcClBl": 478025.97,
        "AccountName": "SALES SGST 2.5%",
        "AccountId": 25764,
        "AcClCrDb": "Cr",
        "GIType": "SGST",
        "IsClear": false
      },
      {
        "AcClBl": 4085963.23,
        "AccountName": "SALES SGST 9%",
        "AccountId": 25770,
        "AcClCrDb": "Cr",
        "GIType": "SGST",
        "IsClear": false
      },
      {
        "AcClBl": 0,
        "AccountName": "SALES SGST 14%",
        "AccountId": 25773,
        "AcClCrDb": "Db",
        "GIType": "SGST",
        "IsClear": false
      }
    ]
  },
  3: {
    "CGST#Input": [
      {
        "AcClBl": 390.3,
        "AccountName": "Purchase CGST 1.5%",
        "AccountId": 25900,
        "AcClCrDb": "Db",
        "GIType": "CGST",
        "IsClear": false
      },
      {
        "AcClBl": 304558.11,
        "AccountName": "Purchase CGST 2.5%",
        "AccountId": 25903,
        "AcClCrDb": "Db",
        "GIType": "CGST",
        "IsClear": false
      },
      {
        "AcClBl": 5316,
        "AccountName": "Purchase CGST 6%",
        "AccountId": 25906,
        "AcClCrDb": "Db",
        "GIType": "CGST",
        "IsClear": false
      },
      {
        "AcClBl": 6363187.72,
        "AccountName": "Purchase CGST 9%",
        "AccountId": 25909,
        "AcClCrDb": "Db",
        "GIType": "CGST",
        "IsClear": false
      },
      {
        "AcClBl": 0,
        "AccountName": "Purchase CGST 14%",
        "AccountId": 25912,
        "AcClCrDb": "Db",
        "GIType": "CGST",
        "IsClear": false
      }
    ],
    "IGST#Input": [
      {
        "AcClBl": 0,
        "AccountName": "Purchase IGST 3%",
        "AccountId": 25902,
        "AcClCrDb": "Db",
        "GIType": "IGST",
        "IsClear": false
      },
      {
        "AcClBl": 0,
        "AccountName": "Purchase IGST 5%",
        "AccountId": 25905,
        "AcClCrDb": "Db",
        "GIType": "IGST",
        "IsClear": false
      },
      {
        "AcClBl": 0,
        "AccountName": "Purchase IGST 12%",
        "AccountId": 25908,
        "AcClCrDb": "Db",
        "GIType": "IGST",
        "IsClear": false
      },
      {
        "AcClBl": 0,
        "AccountName": "Purchase IGST 18%",
        "AccountId": 25911,
        "AcClCrDb": "Db",
        "GIType": "IGST",
        "IsClear": false
      },
      {
        "AcClBl": 0,
        "AccountName": "Purchase IGST 28%",
        "AccountId": 25914,
        "AcClCrDb": "Db",
        "GIType": "IGST",
        "IsClear": false
      }
    ],
    "SGST#Input": [
      {
        "AcClBl": 304558.11,
        "AccountName": "Purchase SGST 2.5%",
        "AccountId": 25904,
        "AcClCrDb": "Db",
        "GIType": "SGST",
        "IsClear": false
      },
      {
        "AcClBl": 5316,
        "AccountName": "Purchase SGST 6%",
        "AccountId": 25907,
        "AcClCrDb": "Db",
        "GIType": "SGST",
        "IsClear": false
      },
      {
        "AcClBl": 6363187.72,
        "AccountName": "Purchase SGST 9%",
        "AccountId": 25910,
        "AcClCrDb": "Db",
        "GIType": "SGST",
        "IsClear": false
      },
      {
        "AcClBl": 0,
        "AccountName": "Purchase SGST 14%",
        "AccountId": 25913,
        "AcClCrDb": "Db",
        "GIType": "SGST",
        "IsClear": false
      }
    ],
    "CGST#Output": [
      {
        "AcClBl": 0,
        "AccountName": "SALES CGST 1.5%",
        "AccountId": 25776,
        "AcClCrDb": "Db",
        "GIType": "CGST",
        "IsClear": false
      },
      {
        "AcClBl": 478025.97,
        "AccountName": "SALES CGST 2.5%",
        "AccountId": 25763,
        "AcClCrDb": "Cr",
        "GIType": "CGST",
        "IsClear": false
      },
      {
        "AcClBl": 7976.12,
        "AccountName": "SALES CGST 6%",
        "AccountId": 25766,
        "AcClCrDb": "Cr",
        "GIType": "CGST",
        "IsClear": false
      },
      {
        "AcClBl": 4085963.23,
        "AccountName": "SALES CGST 9%",
        "AccountId": 25769,
        "AcClCrDb": "Cr",
        "GIType": "CGST",
        "IsClear": false
      },
      {
        "AcClBl": 0,
        "AccountName": "SALES CGST 14%",
        "AccountId": 25772,
        "AcClCrDb": "Db",
        "GIType": "CGST",
        "IsClear": false
      }
    ],
    "IGST#Output": [
      {
        "AcClBl": 0,
        "AccountName": "SALES IGST 3%",
        "AccountId": 25778,
        "AcClCrDb": "Db",
        "GIType": "IGST",
        "IsClear": false
      },
      {
        "AcClBl": 466266.45,
        "AccountName": "SALES IGST 5%",
        "AccountId": 25765,
        "AcClCrDb": "Cr",
        "GIType": "IGST",
        "IsClear": false
      },
      {
        "AcClBl": 23604,
        "AccountName": "SALES IGST 12%",
        "AccountId": 25768,
        "AcClCrDb": "Cr",
        "GIType": "IGST",
        "IsClear": false
      },
      {
        "AcClBl": 8160677.94,
        "AccountName": "SALES IGST 18%",
        "AccountId": 25771,
        "AcClCrDb": "Cr",
        "GIType": "IGST",
        "IsClear": false
      },
      {
        "AcClBl": 0,
        "AccountName": "SALES IGST 28%",
        "AccountId": 25774,
        "AcClCrDb": "Db",
        "GIType": "IGST",
        "IsClear": false
      }
    ],
    "SGST#Output": [
      {
        "AcClBl": 0,
        "AccountName": "SALES SGST 1.5%",
        "AccountId": 25777,
        "AcClCrDb": "Db",
        "GIType": "SGST",
        "IsClear": false
      },
      {
        "AcClBl": 478025.97,
        "AccountName": "SALES SGST 2.5%",
        "AccountId": 25764,
        "AcClCrDb": "Cr",
        "GIType": "SGST",
        "IsClear": false
      },
      {
        "AcClBl": 4085963.23,
        "AccountName": "SALES SGST 9%",
        "AccountId": 25770,
        "AcClCrDb": "Cr",
        "GIType": "SGST",
        "IsClear": false
      },
      {
        "AcClBl": 0,
        "AccountName": "SALES SGST 14%",
        "AccountId": 25773,
        "AcClCrDb": "Db",
        "GIType": "SGST",
        "IsClear": false
      }
    ]
  },
}