export const GSTDATA = {
    1: {
        "CGST#Input": [
            {
                "AcClBl": 390.3,
                "AccountName": "Purchase CGST 1.5%",
                "AccountId": 25900,
                "AcClCrDb": "Db",
                "GIType": "CGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input",
            },
            {
                "AcClBl": 304558.11,
                "AccountName": "Purchase CGST 2.5%",
                "AccountId": 25903,
                "AcClCrDb": "Db",
                "GIType": "CGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input",
            },
            {
                "AcClBl": 5316,
                "AccountName": "Purchase CGST 6%",
                "AccountId": 25906,
                "AcClCrDb": "Db",
                "GIType": "CGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input",
            },
            {
                "AcClBl": 6363187.72,
                "AccountName": "Purchase CGST 9%",
                "AccountId": 25909,
                "AcClCrDb": "Db",
                "GIType": "CGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input",
            },
            {
                "AcClBl": 0,
                "AccountName": "Purchase CGST 14%",
                "AccountId": 25912,
                "AcClCrDb": "Db",
                "GIType": "CGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input",
            }
        ],
        "IGST#Input": [
            {
                "AcClBl": 0,
                "AccountName": "Purchase IGST 3%",
                "AccountId": 25902,
                "AcClCrDb": "Db",
                "GIType": "IGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input"
            },
            {
                "AcClBl": 0,
                "AccountName": "Purchase IGST 5%",
                "AccountId": 25905,
                "AcClCrDb": "Db",
                "GIType": "IGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input"
            },
            {
                "AcClBl": 0,
                "AccountName": "Purchase IGST 12%",
                "AccountId": 25908,
                "AcClCrDb": "Db",
                "GIType": "IGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input"
            },
            {
                "AcClBl": 0,
                "AccountName": "Purchase IGST 18%",
                "AccountId": 25911,
                "AcClCrDb": "Db",
                "GIType": "IGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input"
            },
            {
                "AcClBl": 0,
                "AccountName": "Purchase IGST 28%",
                "AccountId": 25914,
                "AcClCrDb": "Db",
                "GIType": "IGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input"
            }
        ],
        "SGST#Input": [
            {
                "AcClBl": 304558.11,
                "AccountName": "Purchase SGST 2.5%",
                "AccountId": 25904,
                "AcClCrDb": "Db",
                "GIType": "SGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input"
            },
            {
                "AcClBl": 5316,
                "AccountName": "Purchase SGST 6%",
                "AccountId": 25907,
                "AcClCrDb": "Db",
                "GIType": "SGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input"
            },
            {
                "AcClBl": 6363187.72,
                "AccountName": "Purchase SGST 9%",
                "AccountId": 25910,
                "AcClCrDb": "Db",
                "GIType": "SGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input"
            },
            {
                "AcClBl": 0,
                "AccountName": "Purchase SGST 14%",
                "AccountId": 25913,
                "AcClCrDb": "Db",
                "GIType": "SGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input"
            }
        ],
        "CGST#Output": [
            {
                "AcClBl": 0,
                "AccountName": "SALES CGST 1.5%",
                "AccountId": 25776,
                "AcClCrDb": "Db",
                "GIType": "CGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Output"
            },
            {
                "AcClBl": 478025.97,
                "AccountName": "SALES CGST 2.5%",
                "AccountId": 25763,
                "AcClCrDb": "Cr",
                "GIType": "CGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Output"
            },
            {
                "AcClBl": 7976.12,
                "AccountName": "SALES CGST 6%",
                "AccountId": 25766,
                "AcClCrDb": "Cr",
                "GIType": "CGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Output"
            },
            {
                "AcClBl": 4085963.23,
                "AccountName": "SALES CGST 9%",
                "AccountId": 25769,
                "AcClCrDb": "Cr",
                "GIType": "CGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Output"
            },
            {
                "AcClBl": 0,
                "AccountName": "SALES CGST 14%",
                "AccountId": 25772,
                "AcClCrDb": "Db",
                "GIType": "CGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Output"
            }
        ],
        "IGST#Output": [
            {
                "AcClBl": 0,
                "AccountName": "SALES IGST 3%",
                "AccountId": 25778,
                "AcClCrDb": "Db",
                "GIType": "IGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Output"
            },
            {
                "AcClBl": 466266.45,
                "AccountName": "SALES IGST 5%",
                "AccountId": 25765,
                "AcClCrDb": "Cr",
                "GIType": "IGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Output"
            },
            {
                "AcClBl": 23604,
                "AccountName": "SALES IGST 12%",
                "AccountId": 25768,
                "AcClCrDb": "Cr",
                "GIType": "IGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Output"
            },
            {
                "AcClBl": 8160677.94,
                "AccountName": "SALES IGST 18%",
                "AccountId": 25771,
                "AcClCrDb": "Cr",
                "GIType": "IGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Output"
            },
            {
                "AcClBl": 0,
                "AccountName": "SALES IGST 28%",
                "AccountId": 25774,
                "AcClCrDb": "Db",
                "GIType": "IGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Output"
            }
        ],
        "SGST#Output": [
            {
                "AcClBl": 0,
                "AccountName": "SALES SGST 1.5%",
                "AccountId": 25777,
                "AcClCrDb": "Db",
                "GIType": "SGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Output"
            },
            {
                "AcClBl": 478025.97,
                "AccountName": "SALES SGST 2.5%",
                "AccountId": 25764,
                "AcClCrDb": "Cr",
                "GIType": "SGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Output"
            },
            {
                "AcClBl": 4085963.23,
                "AccountName": "SALES SGST 9%",
                "AccountId": 25770,
                "AcClCrDb": "Cr",
                "GIType": "SGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Output"
            },
            {
                "AcClBl": 0,
                "AccountName": "SALES SGST 14%",
                "AccountId": 25773,
                "AcClCrDb": "Db",
                "GIType": "SGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Output"
            }
        ]
    },
    2: {
        "CGST#Input": [
            {
                "AcClBl": 5,
                "AccountName": "Purchase CGST 1.5%",
                "AccountId": 25900,
                "AcClCrDb": "Db",
                "GIType": "CGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input",
            },
            {
                "AcClBl": 50,
                "AccountName": "Purchase CGST 2.5%",
                "AccountId": 25903,
                "AcClCrDb": "Db",
                "GIType": "CGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input",
            },
            {
                "AcClBl": 500,
                "AccountName": "Purchase CGST 6%",
                "AccountId": 25906,
                "AcClCrDb": "Db",
                "GIType": "CGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input",
            },
            {
                "AcClBl": 2500,
                "AccountName": "Purchase CGST 9%",
                "AccountId": 25909,
                "AcClCrDb": "Db",
                "GIType": "CGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input",
            },
            {
                "AcClBl": 10000,
                "AccountName": "Purchase CGST 14%",
                "AccountId": 25912,
                "AcClCrDb": "Db",
                "GIType": "CGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input",
            }
        ],
        "CGST#Output": [
            {
                "AcClBl": 2,
                "AccountName": "SALES CGST 1.5%",
                "AccountId": 25776,
                "AcClCrDb": "Db",
                "GIType": "CGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType": "Output"
            },
            {
                "AcClBl": 100,
                "AccountName": "SALES CGST 2.5%",
                "AccountId": 25763,
                "AcClCrDb": "Cr",
                "GIType": "CGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType": "Output"
            },
            {
                "AcClBl": 25,
                "AccountName": "SALES CGST 6%",
                "AccountId": 25766,
                "AcClCrDb": "Cr",
                "GIType": "CGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType": "Output"
            },
            {
                "AcClBl": 30000,
                "AccountName": "SALES CGST 9%",
                "AccountId": 25769,
                "AcClCrDb": "Cr",
                "GIType": "CGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType": "Output"
            },
            {
                "AcClBl": 20000,
                "AccountName": "SALES CGST 14%",
                "AccountId": 25772,
                "AcClCrDb": "Db",
                "GIType": "CGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType": "Output"
            }
        ],
        "IGST#Input": [
            {
                "AcClBl": 0,
                "AccountName": "Purchase IGST 3%",
                "AccountId": 25902,
                "AcClCrDb": "Db",
                "GIType": "IGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input"
            },
            {
                "AcClBl": 0,
                "AccountName": "Purchase IGST 5%",
                "AccountId": 25905,
                "AcClCrDb": "Db",
                "GIType": "IGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input"
            },
            {
                "AcClBl": 0,
                "AccountName": "Purchase IGST 12%",
                "AccountId": 25908,
                "AcClCrDb": "Db",
                "GIType": "IGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input"
            },
            {
                "AcClBl": 0,
                "AccountName": "Purchase IGST 18%",
                "AccountId": 25911,
                "AcClCrDb": "Db",
                "GIType": "IGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input"
            },
            {
                "AcClBl": 0,
                "AccountName": "Purchase IGST 28%",
                "AccountId": 25914,
                "AcClCrDb": "Db",
                "GIType": "IGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input"
            }
        ],
        "SGST#Input": [
            {
                "AcClBl": 304558.11,
                "AccountName": "Purchase SGST 2.5%",
                "AccountId": 25904,
                "AcClCrDb": "Db",
                "GIType": "SGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input"
            },
            {
                "AcClBl": 5316,
                "AccountName": "Purchase SGST 6%",
                "AccountId": 25907,
                "AcClCrDb": "Db",
                "GIType": "SGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input"
            },
            {
                "AcClBl": 6363187.72,
                "AccountName": "Purchase SGST 9%",
                "AccountId": 25910,
                "AcClCrDb": "Db",
                "GIType": "SGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input"
            },
            {
                "AcClBl": 0,
                "AccountName": "Purchase SGST 14%",
                "AccountId": 25913,
                "AcClCrDb": "Db",
                "GIType": "SGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input"
            }
        ],
        "IGST#Output": [
            {
                "AcClBl": 0,
                "AccountName": "SALES IGST 3%",
                "AccountId": 25778,
                "AcClCrDb": "Db",
                "GIType": "IGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Output"
            },
            {
                "AcClBl": 466266.45,
                "AccountName": "SALES IGST 5%",
                "AccountId": 25765,
                "AcClCrDb": "Cr",
                "GIType": "IGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Output"
            },
            {
                "AcClBl": 23604,
                "AccountName": "SALES IGST 12%",
                "AccountId": 25768,
                "AcClCrDb": "Cr",
                "GIType": "IGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Output"
            },
            {
                "AcClBl": 8160677.94,
                "AccountName": "SALES IGST 18%",
                "AccountId": 25771,
                "AcClCrDb": "Cr",
                "GIType": "IGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Output"
            },
            {
                "AcClBl": 0,
                "AccountName": "SALES IGST 28%",
                "AccountId": 25774,
                "AcClCrDb": "Db",
                "GIType": "IGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Output"
            }
        ],
        "SGST#Output": [
            {
                "AcClBl": 0,
                "AccountName": "SALES SGST 1.5%",
                "AccountId": 25777,
                "AcClCrDb": "Db",
                "GIType": "SGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Output"
            },
            {
                "AcClBl": 478025.97,
                "AccountName": "SALES SGST 2.5%",
                "AccountId": 25764,
                "AcClCrDb": "Cr",
                "GIType": "SGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Output"
            },
            {
                "AcClBl": 4085963.23,
                "AccountName": "SALES SGST 9%",
                "AccountId": 25770,
                "AcClCrDb": "Cr",
                "GIType": "SGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Output"
            },
            {
                "AcClBl": 0,
                "AccountName": "SALES SGST 14%",
                "AccountId": 25773,
                "AcClCrDb": "Db",
                "GIType": "SGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Output"
            }
        ]
    },
    3: {
        "CGST#Input": [
            {
                "AcClBl": 5000,
                "AccountName": "Purchase CGST 1.5%",
                "AccountId": 25900,
                "AcClCrDb": "Db",
                "GIType": "CGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input",
            },
            {
                "AcClBl": 75343,
                "AccountName": "Purchase CGST 2.5%",
                "AccountId": 25903,
                "AcClCrDb": "Db",
                "GIType": "CGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input",
            },
            {
                "AcClBl": 121267,
                "AccountName": "Purchase CGST 6%",
                "AccountId": 25906,
                "AcClCrDb": "Db",
                "GIType": "CGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input",
            },
            {
                "AcClBl": 0,
                "AccountName": "Purchase CGST 9%",
                "AccountId": 25909,
                "AcClCrDb": "Db",
                "GIType": "CGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input",
            },
            {
                "AcClBl": 998273,
                "AccountName": "Purchase CGST 14%",
                "AccountId": 25912,
                "AcClCrDb": "Db",
                "GIType": "CGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input",
            }
        ],
        "CGST#Output": [
            {
                "AcClBl": 25632,
                "AccountName": "SALES CGST 1.5%",
                "AccountId": 25776,
                "AcClCrDb": "Db",
                "GIType": "CGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType": "Output"
            },
            {
                "AcClBl": 32000,
                "AccountName": "SALES CGST 2.5%",
                "AccountId": 25763,
                "AcClCrDb": "Cr",
                "GIType": "CGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType": "Output"
            },
            {
                "AcClBl": 10000,
                "AccountName": "SALES CGST 6%",
                "AccountId": 25766,
                "AcClCrDb": "Cr",
                "GIType": "CGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType": "Output"
            },
            {
                "AcClBl": 5001,
                "AccountName": "SALES CGST 9%",
                "AccountId": 25769,
                "AcClCrDb": "Cr",
                "GIType": "CGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType": "Output"
            },
            {
                "AcClBl": 23242,
                "AccountName": "SALES CGST 14%",
                "AccountId": 25772,
                "AcClCrDb": "Db",
                "GIType": "CGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType": "Output"
            }
        ],
        "IGST#Input": [
            {
                "AcClBl": 0,
                "AccountName": "Purchase IGST 3%",
                "AccountId": 25902,
                "AcClCrDb": "Db",
                "GIType": "IGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input"
            },
            {
                "AcClBl": 0,
                "AccountName": "Purchase IGST 5%",
                "AccountId": 25905,
                "AcClCrDb": "Db",
                "GIType": "IGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input"
            },
            {
                "AcClBl": 0,
                "AccountName": "Purchase IGST 12%",
                "AccountId": 25908,
                "AcClCrDb": "Db",
                "GIType": "IGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input"
            },
            {
                "AcClBl": 0,
                "AccountName": "Purchase IGST 18%",
                "AccountId": 25911,
                "AcClCrDb": "Db",
                "GIType": "IGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input"
            },
            {
                "AcClBl": 0,
                "AccountName": "Purchase IGST 28%",
                "AccountId": 25914,
                "AcClCrDb": "Db",
                "GIType": "IGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input"
            }
        ],
        "SGST#Input": [
            {
                "AcClBl": 304558.11,
                "AccountName": "Purchase SGST 2.5%",
                "AccountId": 25904,
                "AcClCrDb": "Db",
                "GIType": "SGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input"
            },
            {
                "AcClBl": 5316,
                "AccountName": "Purchase SGST 6%",
                "AccountId": 25907,
                "AcClCrDb": "Db",
                "GIType": "SGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input"
            },
            {
                "AcClBl": 6363187.72,
                "AccountName": "Purchase SGST 9%",
                "AccountId": 25910,
                "AcClCrDb": "Db",
                "GIType": "SGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input"
            },
            {
                "AcClBl": 0,
                "AccountName": "Purchase SGST 14%",
                "AccountId": 25913,
                "AcClCrDb": "Db",
                "GIType": "SGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Input"
            }
        ],
        "IGST#Output": [
            {
                "AcClBl": 0,
                "AccountName": "SALES IGST 3%",
                "AccountId": 25778,
                "AcClCrDb": "Db",
                "GIType": "IGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Output"
            },
            {
                "AcClBl": 466266.45,
                "AccountName": "SALES IGST 5%",
                "AccountId": 25765,
                "AcClCrDb": "Cr",
                "GIType": "IGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Output"
            },
            {
                "AcClBl": 23604,
                "AccountName": "SALES IGST 12%",
                "AccountId": 25768,
                "AcClCrDb": "Cr",
                "GIType": "IGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Output"
            },
            {
                "AcClBl": 8160677.94,
                "AccountName": "SALES IGST 18%",
                "AccountId": 25771,
                "AcClCrDb": "Cr",
                "GIType": "IGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Output"
            },
            {
                "AcClBl": 0,
                "AccountName": "SALES IGST 28%",
                "AccountId": 25774,
                "AcClCrDb": "Db",
                "GIType": "IGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Output"
            }
        ],
        "SGST#Output": [
            {
                "AcClBl": 0,
                "AccountName": "SALES SGST 1.5%",
                "AccountId": 25777,
                "AcClCrDb": "Db",
                "GIType": "SGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Output"
            },
            {
                "AcClBl": 478025.97,
                "AccountName": "SALES SGST 2.5%",
                "AccountId": 25764,
                "AcClCrDb": "Cr",
                "GIType": "SGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Output"
            },
            {
                "AcClBl": 4085963.23,
                "AccountName": "SALES SGST 9%",
                "AccountId": 25770,
                "AcClCrDb": "Cr",
                "GIType": "SGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Output"
            },
            {
                "AcClBl": 0,
                "AccountName": "SALES SGST 14%",
                "AccountId": 25773,
                "AcClCrDb": "Db",
                "GIType": "SGST",
                "IsClear": false,
                "MainId": 9,
                "AccSubType":"Output"
            }
        ]
    },
}

export const CASHACCOUNT = [
    {
        "city": null,
        "OppAccountId": 25165,
        "IsAudit": false,
        "Audit": "",
        "OppAccountName": "Cash Ledger -CGST-",
        "AccountId": 25165,
        "BID": 1,
        "AccountName": "Cash Ledger -CGST-",
        "Alias": null,
        "MainId": 52,
        "AccGroupId": 1080,
        "Actype": "No",
        "Tax_mstid": 38,
        "OpBalance": 351,
        "dbcr": "Db",
        "CreditLimit": null,
        "CreditDay": null,
        "STNO": null,
        "CSTNO": null,
        "TINNO": null,
        "ECCNO": null,
        "TDSNO": null,
        "PANNO": null,
        "SERTEXNO": null,
        "Address": null,
        "Address2": null,
        "Address3": null,
        "cityid": "0",
        "PhoneO": null,
        "PhoneR": null,
        "Mobile": null,
        "Mobile2": null,
        "Fax": null,
        "PinCode": null,
        "BirthDate": null,
        "WedDate": null,
        "Email": null,
        "Website": null,
        "Capital": null,
        "Profit": null,
        "Loss": null,
        "Depriciation": null,
        "DepriAccountId": null,
        "Interest": null,
        "InterestAccountId": null,
        "Trade": null,
        "P_L": null,
        "Trail": true,
        "BalSheet": true,
        "Pamt": true,
        "Rcpt": true,
        "Ctra": null,
        "Sale": null,
        "Salevch": true,
        "Prch": null,
        "Prchvch": true,
        "Cash": null,
        "Bank": null,
        "Salprc": null,
        "Tax": true,
        "Party": null,
        "Stk": null,
        "BalanceMethod": "Balance Only",
        "ImagePath": null,
        "vchtype": null,
        "ContactPerson": null,
        "ContactPerson2": null,
        "TransportId": null,
        "Book_code": null,
        "Message": null,
        "FirstUID": 20,
        "ModDate": "2024-03-08T15:43:29",
        "CreatedTime": "2023-04-01T00:00:00",
        "UID": 25,
        "CashDebit": null,
        "BrokerAccountId": null,
        "BroReq": null,
        "IsComAgent": null,
        "BroRate": null,
        "BillingReq": null,
        "AccountType": null,
        "RateId": null,
        "MistryId": null,
        "RepresentativeId": null,
        "TDSCrDb": null,
        "TDSReq": null,
        "TDSRate": null,
        "TDSAmount": null,
        "TDSAccountId": null,
        "IsMember": null,
        "CENO": null,
        "ERange": null,
        "Division": null,
        "Commisinerate": null,
        "DueDate": null,
        "PcAmount": null,
        "SBook_code": null,
        "GUIDC": "aaaf808f-93fa-43fb-a0d1-c1de3a3cec1c",
        "InvoiceId": null,
        "Docno": null,
        "Address4": null,
        "DeActive": false,
        "AreaId": null,
        "BroType": null,
        "MultiCurrency": null,
        "IsDeleted": null,
        "GSTNO": null,
        "AdharNo": null,
        "stateid": 37,
        "StateName": null,
        "RegType": null,
        "ExportType": null,
        "GIType": "CGST",
        "SalaryAmount": null,
        "CalDays": null,
        "S_L": null,
        "Salary": null,
        "JoiningDate": null,
        "ResignDate": null,
        "WorkingDays": null,
        "UF_FERTLICNO": null,
        "UF_Pesticidelicenceno": null,
        "UF_seedslicenceno": null,
        "UF_Dealerformno": null,
        "UF_Dealerappointedby": null,
        "UF_appointeddate": null,
        "UF_Securitychequeno1": null,
        "UF_Securitychequeno2": null,
        "UF_Securitydepositechqno": null,
        "UF_securitydepositechqdate": null,
        "UF_Securitydepositers": null,
        "PartyTypeId": null,
        "PartyCategoryId": null,
        "UF_FERLICUPTO": null,
        "UF_PESLICUPTO": null,
        "UF_SEEDLICUPTO": null,
        "UF_blnk": null,
        "BankAccountId": null,
        "BankBranchName": null,
        "BankAccNo": null,
        "BankIFSCCode": null,
        "BankAddress": null,
        "BankName": null,
        "BankAccountType": null,
        "InterestRec": null,
        "Locked": false,
        "TDSSecId": null,
        "TDSDeclaration": null,
        "NoofTrucks": null,
        "DefaultBankId": null,
        "BankId2": null,
        "BankId3": null,
        "BankId4": null,
        "LocationId": null,
        "MUID": null,
        "TCSId": null,
        "IncludeSaleDisc": null,
        "DiscountType": null,
        "AccSubType": "Output",
        "DeActiveFyrid": null,
        "MSME": null,
        "AddCreditDay": null,
        "AddCreditLimit": null
    },
    {
        "city": null,
        "OppAccountId": 25175,
        "IsAudit": false,
        "Audit": "",
        "OppAccountName": "Cash Ledger -IGST-",
        "AccountId": 25175,
        "BID": 1,
        "AccountName": "Cash Ledger -IGST-",
        "Alias": null,
        "MainId": 52,
        "AccGroupId": 1080,
        "Actype": "No",
        "Tax_mstid": 38,
        "OpBalance": 80,
        "dbcr": "Db",
        "CreditLimit": null,
        "CreditDay": null,
        "STNO": null,
        "CSTNO": null,
        "TINNO": null,
        "ECCNO": null,
        "TDSNO": null,
        "PANNO": null,
        "SERTEXNO": null,
        "Address": null,
        "Address2": null,
        "Address3": null,
        "cityid": "0",
        "PhoneO": null,
        "PhoneR": null,
        "Mobile": null,
        "Mobile2": null,
        "Fax": null,
        "PinCode": null,
        "BirthDate": null,
        "WedDate": null,
        "Email": null,
        "Website": null,
        "Capital": null,
        "Profit": null,
        "Loss": null,
        "Depriciation": null,
        "DepriAccountId": null,
        "Interest": null,
        "InterestAccountId": null,
        "Trade": null,
        "P_L": null,
        "Trail": true,
        "BalSheet": true,
        "Pamt": true,
        "Rcpt": true,
        "Ctra": null,
        "Sale": null,
        "Salevch": true,
        "Prch": null,
        "Prchvch": true,
        "Cash": null,
        "Bank": null,
        "Salprc": null,
        "Tax": true,
        "Party": null,
        "Stk": null,
        "BalanceMethod": "Balance Only",
        "ImagePath": null,
        "vchtype": null,
        "ContactPerson": null,
        "ContactPerson2": null,
        "TransportId": null,
        "Book_code": null,
        "Message": null,
        "FirstUID": 20,
        "ModDate": "2024-03-08T15:43:52",
        "CreatedTime": "2023-04-01T00:00:00",
        "UID": 25,
        "CashDebit": null,
        "BrokerAccountId": null,
        "BroReq": null,
        "IsComAgent": null,
        "BroRate": null,
        "BillingReq": null,
        "AccountType": null,
        "RateId": null,
        "MistryId": null,
        "RepresentativeId": null,
        "TDSCrDb": null,
        "TDSReq": null,
        "TDSRate": null,
        "TDSAmount": null,
        "TDSAccountId": null,
        "IsMember": null,
        "CENO": null,
        "ERange": null,
        "Division": null,
        "Commisinerate": null,
        "DueDate": null,
        "PcAmount": null,
        "SBook_code": null,
        "GUIDC": "4a8f3733-b5cf-4201-9479-94b9b7f35fe2",
        "InvoiceId": null,
        "Docno": null,
        "Address4": null,
        "DeActive": false,
        "AreaId": null,
        "BroType": null,
        "MultiCurrency": null,
        "IsDeleted": null,
        "GSTNO": null,
        "AdharNo": null,
        "stateid": 37,
        "StateName": null,
        "RegType": null,
        "ExportType": null,
        "GIType": "IGST",
        "SalaryAmount": null,
        "CalDays": null,
        "S_L": null,
        "Salary": null,
        "JoiningDate": null,
        "ResignDate": null,
        "WorkingDays": null,
        "UF_FERTLICNO": null,
        "UF_Pesticidelicenceno": null,
        "UF_seedslicenceno": null,
        "UF_Dealerformno": null,
        "UF_Dealerappointedby": null,
        "UF_appointeddate": null,
        "UF_Securitychequeno1": null,
        "UF_Securitychequeno2": null,
        "UF_Securitydepositechqno": null,
        "UF_securitydepositechqdate": null,
        "UF_Securitydepositers": null,
        "PartyTypeId": null,
        "PartyCategoryId": null,
        "UF_FERLICUPTO": null,
        "UF_PESLICUPTO": null,
        "UF_SEEDLICUPTO": null,
        "UF_blnk": null,
        "BankAccountId": null,
        "BankBranchName": null,
        "BankAccNo": null,
        "BankIFSCCode": null,
        "BankAddress": null,
        "BankName": null,
        "BankAccountType": null,
        "InterestRec": null,
        "Locked": false,
        "TDSSecId": null,
        "TDSDeclaration": null,
        "NoofTrucks": null,
        "DefaultBankId": null,
        "BankId2": null,
        "BankId3": null,
        "BankId4": null,
        "LocationId": null,
        "MUID": null,
        "TCSId": null,
        "IncludeSaleDisc": null,
        "DiscountType": null,
        "AccSubType": "Output",
        "DeActiveFyrid": null,
        "MSME": null,
        "AddCreditDay": null,
        "AddCreditLimit": null
    },
    {
        "city": null,
        "OppAccountId": 25180,
        "IsAudit": false,
        "Audit": "",
        "OppAccountName": "Cash Ledger -SGST-",
        "AccountId": 25180,
        "BID": 1,
        "AccountName": "Cash Ledger -SGST-",
        "Alias": null,
        "MainId": 52,
        "AccGroupId": 1080,
        "Actype": "No",
        "Tax_mstid": 38,
        "OpBalance": 101,
        "dbcr": "Db",
        "CreditLimit": null,
        "CreditDay": null,
        "STNO": null,
        "CSTNO": null,
        "TINNO": null,
        "ECCNO": null,
        "TDSNO": null,
        "PANNO": null,
        "SERTEXNO": null,
        "Address": null,
        "Address2": null,
        "Address3": null,
        "cityid": "0",
        "PhoneO": null,
        "PhoneR": null,
        "Mobile": null,
        "Mobile2": null,
        "Fax": null,
        "PinCode": null,
        "BirthDate": null,
        "WedDate": null,
        "Email": null,
        "Website": null,
        "Capital": null,
        "Profit": null,
        "Loss": null,
        "Depriciation": null,
        "DepriAccountId": null,
        "Interest": null,
        "InterestAccountId": null,
        "Trade": null,
        "P_L": null,
        "Trail": true,
        "BalSheet": true,
        "Pamt": true,
        "Rcpt": true,
        "Ctra": null,
        "Sale": null,
        "Salevch": true,
        "Prch": null,
        "Prchvch": true,
        "Cash": null,
        "Bank": null,
        "Salprc": null,
        "Tax": true,
        "Party": null,
        "Stk": null,
        "BalanceMethod": "Balance Only",
        "ImagePath": null,
        "vchtype": null,
        "ContactPerson": null,
        "ContactPerson2": null,
        "TransportId": null,
        "Book_code": null,
        "Message": null,
        "FirstUID": 20,
        "ModDate": "2024-03-08T15:44:13",
        "CreatedTime": "2023-04-01T00:00:00",
        "UID": 25,
        "CashDebit": null,
        "BrokerAccountId": null,
        "BroReq": null,
        "IsComAgent": null,
        "BroRate": null,
        "BillingReq": null,
        "AccountType": null,
        "RateId": null,
        "MistryId": null,
        "RepresentativeId": null,
        "TDSCrDb": null,
        "TDSReq": null,
        "TDSRate": null,
        "TDSAmount": null,
        "TDSAccountId": null,
        "IsMember": null,
        "CENO": null,
        "ERange": null,
        "Division": null,
        "Commisinerate": null,
        "DueDate": null,
        "PcAmount": null,
        "SBook_code": null,
        "GUIDC": "cfbe3854-97f9-47d2-8230-28f4c612969e",
        "InvoiceId": null,
        "Docno": null,
        "Address4": null,
        "DeActive": false,
        "AreaId": null,
        "BroType": null,
        "MultiCurrency": null,
        "IsDeleted": null,
        "GSTNO": null,
        "AdharNo": null,
        "stateid": 37,
        "StateName": null,
        "RegType": null,
        "ExportType": null,
        "GIType": "SGST",
        "SalaryAmount": null,
        "CalDays": null,
        "S_L": null,
        "Salary": null,
        "JoiningDate": null,
        "ResignDate": null,
        "WorkingDays": null,
        "UF_FERTLICNO": null,
        "UF_Pesticidelicenceno": null,
        "UF_seedslicenceno": null,
        "UF_Dealerformno": null,
        "UF_Dealerappointedby": null,
        "UF_appointeddate": null,
        "UF_Securitychequeno1": null,
        "UF_Securitychequeno2": null,
        "UF_Securitydepositechqno": null,
        "UF_securitydepositechqdate": null,
        "UF_Securitydepositers": null,
        "PartyTypeId": null,
        "PartyCategoryId": null,
        "UF_FERLICUPTO": null,
        "UF_PESLICUPTO": null,
        "UF_SEEDLICUPTO": null,
        "UF_blnk": null,
        "BankAccountId": null,
        "BankBranchName": null,
        "BankAccNo": null,
        "BankIFSCCode": null,
        "BankAddress": null,
        "BankName": null,
        "BankAccountType": null,
        "InterestRec": null,
        "Locked": false,
        "TDSSecId": null,
        "TDSDeclaration": null,
        "NoofTrucks": null,
        "DefaultBankId": null,
        "BankId2": null,
        "BankId3": null,
        "BankId4": null,
        "LocationId": null,
        "MUID": null,
        "TCSId": null,
        "IncludeSaleDisc": null,
        "DiscountType": null,
        "AccSubType": "Output",
        "DeActiveFyrid": null,
        "MSME": null,
        "AddCreditDay": null,
        "AddCreditLimit": null
    }
]

export const NEWCASHACCOUNT = [
    {
        "OppAccountId": 25165,
        "OppAccountName": "Cash Ledger -CGST-",
        "AccountId": 25165,
        "AccountName": "Cash Ledger -CGST-",
        "GIType": "CGST",
    },
    {
        "OppAccountId": 25175,
        "OppAccountName": "Cash Ledger -IGST-",
        "AccountId": 25175,
        "AccountName": "Cash Ledger -IGST-",
        "GIType": "IGST",
    },
    {
        "OppAccountId": 25180,
        "OppAccountName": "Cash Ledger -SGST-",
        "AccountId": 25180,
        "AccountName": "Cash Ledger -SGST-",
        "GIType": "SGST",
    }
]